"""Add pgvector

Revision ID: d8699a097ad8
Revises: 0003_add_analysis_tables
Create Date: 2026-08-24 20:34:44.780377
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy

revision: str = 'd8699a097ad8'
down_revision: Union[str, None] = '0003_add_analysis_tables'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('CREATE EXTENSION IF NOT EXISTS vector;')
    op.alter_column('contract_embeddings', 'embedding',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               existing_nullable=True,
               postgresql_using="embedding::text::vector")
    op.create_unique_constraint(None, 'contract_summaries', ['contract_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contract_summaries', type_='unique')
    op.alter_column('contract_embeddings', 'embedding',
               existing_type=pgvector.sqlalchemy.vector.VECTOR(dim=384),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
